version: "3"
services:
  php74:
    image: php:7.4-fpm-alpine
    volumes:
      - ./php8.0:/var/www/php8.0
      - ./php7.4:/var/www/php7.4
    restart: always
    networks:
      pnut:
        ipv4_address: 192.168.0.5
  php80:
    image: php:8.0-rc-fpm-alpine
    volumes:
      - ./php8.0:/var/www/php8.0
      - ./php7.4:/var/www/php7.4
    restart: always
    networks:
      pnut:
        ipv4_address: 192.168.0.4
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=host.docker.internal
    networks:
      pnut:
        ipv4_address: 192.168.0.3
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./logs:/var/www/logs
      - ./php8.0:/var/www/php8.0
      - ./php7.4:/var/www/php7.4
    restart: always
    networks:
      pnut:
        ipv4_address: 192.168.0.2
  node-express:
    image: node:15-alpine3.10
    volumes:
      - ./node-express:/opt/app
    networks:
      pnut:
        ipv4_address: 192.168.0.8
    restart: always
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3
    working_dir: /opt/app
    command: npm run start

# docker network create --gateway=192.168.0.1 --subnet=192.168.0.0/16 pnut
networks:
  pnut:
    external:
      name: pnut
